In [ ]:
import pandas as pd
import numpy as np

In [ ]:
file_path = '/LoansDatasest.csv'
df = pd.read_csv(file_path)

In [ ]:
df.head()

,customer_id,customer_age,customer_income,home_ownership,employment_duration,loan_intent,loan_grade,loan_amnt,loan_int_rate,term_years,historical_default,cred_hist_length,Current_loan_status
0,1.0,22,59000,RENT,123.0,PERSONAL,C,"35,000.00",16.02,10,Y,3,DEFAULT
1,2.0,21,9600,OWN,5.0,EDUCATION,A,"1,000.00",11.14,1,NaN,2,NO DEFAULT
2,3.0,25,9600,MORTGAGE,1.0,MEDICAL,B,"5,500.00",12.87,5,N,3,DEFAULT
3,4.0,23,65500,RENT,4.0,MEDICAL,B,"35,000.00",15.23,10,N,2,DEFAULT
4,5.0,24,54400,RENT,8.0,MEDICAL,B,"35,000.00",14.27,10,Y,4,DEFAULT

In [ ]:
df.describe()

,customer_id,customer_age,employment_duration,loan_int_rate,term_years,cred_hist_length
count,32583.000000,32586.000000,31691.000000,29470.000000,32586.000000,32586.000000
mean,16289.497806,27.732769,4.790161,11.011553,4.761738,5.804026
std,9405.919628,6.360528,4.142746,3.240440,2.471107,4.055078
min,1.000000,3.000000,0.000000,5.420000,1.000000,2.000000
25%,8144.500000,23.000000,2.000000,7.900000,3.000000,3.000000
50%,16288.000000,26.000000,4.000000,10.990000,4.000000,4.000000
75%,24433.500000,30.000000,7.000000,13.470000,7.000000,8.000000
max,32581.000000,144.000000,123.000000,23.220000,10.000000,30.000000

In [ ]:
df.shape

(32586, 13)

In [ ]:
df.columns

Index(['customer_id', 'customer_age', 'customer_income', 'home_ownership',
       'employment_duration', 'loan_intent', 'loan_grade', 'loan_amnt',
       'loan_int_rate', 'term_years', 'historical_default', 'cred_hist_length',
       'Current_loan_status'],
      dtype='object')

In [ ]:
df.isnull().sum()

customer_id                3
customer_age               0
customer_income            0
home_ownership             0
employment_duration      895
loan_intent                0
loan_grade                 0
loan_amnt                  1
loan_int_rate           3116
term_years                 0
historical_default     20737
cred_hist_length           0
Current_loan_status        4
dtype: int64

In [ ]:
df.nunique()

customer_id            32577
customer_age              62
customer_income         4299
home_ownership             4
employment_duration       36
loan_intent                6
loan_grade                 5
loan_amnt                755
loan_int_rate            348
term_years                10
historical_default         2
cred_hist_length          29
Current_loan_status        2
dtype: int64

In [ ]:
df_cleaned = df.dropna(subset=['customer_id', 'loan_amnt', 'loan_int_rate', 'employment_duration', 'Current_loan_status'])

In [ ]:
df_cleaned.shape

(28638, 13)

In [ ]:
df_cleaned['customer_income'] = df_cleaned['customer_income'].replace('[£,]', '', regex=True).astype(float)
df_cleaned['loan_amnt'] = df_cleaned['loan_amnt'].replace('[£,]', '', regex=True).astype(float)

<ipython-input-13-5c801cf62c00>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['customer_income'] = df_cleaned['customer_income'].replace('[£,]', '', regex=True).astype(float)
<ipython-input-13-5c801cf62c00>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['loan_amnt'] = df_cleaned['loan_amnt'].replace('[£,]', '', regex=True).astype(float)

In [ ]:
df_cleaned['historical_default'] = df_cleaned['historical_default'].fillna('Unknown')

<ipython-input-14-f301bdea068b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['historical_default'] = df_cleaned['historical_default'].fillna('Unknown')

In [ ]:
df_cleaned.head()

,customer_id,customer_age,customer_income,home_ownership,employment_duration,loan_intent,loan_grade,loan_amnt,loan_int_rate,term_years,historical_default,cred_hist_length,Current_loan_status
0,1.0,22,59000.0,RENT,123.0,PERSONAL,C,35000.0,16.02,10,Y,3,DEFAULT
1,2.0,21,9600.0,OWN,5.0,EDUCATION,A,1000.0,11.14,1,Unknown,2,NO DEFAULT
2,3.0,25,9600.0,MORTGAGE,1.0,MEDICAL,B,5500.0,12.87,5,N,3,DEFAULT
3,4.0,23,65500.0,RENT,4.0,MEDICAL,B,35000.0,15.23,10,N,2,DEFAULT
4,5.0,24,54400.0,RENT,8.0,MEDICAL,B,35000.0,14.27,10,Y,4,DEFAULT

In [ ]:
df_cleaned.to_csv('/content/HCD(Preprocessed).csv', index=False)